export const product = [
    {
        id:0,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Kurvi Crackers',
        price:520,
    },
    {
        id:1,
        image: '/IMAGES/lakshmi-img-2.jpg',
        title:'Lakshmi Crackers',
        price:220,
    },
    {
        id:2,
        image: '/IMAGES/helicopter-img-3.jpg',
        title:'Helicopter Crackers',
        price:320,
    },
    {
        id:3,
        image: '/IMAGES/helicopter-img-3.jpg',
        title:'Paper Crackers',
        price:160,
    },
    {
        id:4,
        image: '/IMAGES/lakshmi-img-2.jpg',
        title:'15 Spot Crackers',
        price:300,
    },
    {
        id:5,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:6,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:7,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:8,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:9,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:10,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:11,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:12,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:13,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:14,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:15,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:16,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:17,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:18,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:19,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:20,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:21,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:22,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        price:400,
    },
    {
        id:23,
        image: '/IMAGES/lakshmi-img-2.jpg',
        title:'15 Spot Crackers',
        price:300,
    }
];