export const product = [
    {
        id:0,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Kurvi Crackers',
        description: 'Kurvi Crackers are known for their vibrant display and loud bursts. These crackers are shaped like small cones, and when lit, they spin on the ground, emitting bright, colorful sparks. Perfect for lighting up festive nights with a spectacular show.',
        price:520,
    },
    {
        id:1,
        image: '/IMAGES/lakshmi-img-2.jpg',
        title:'Lakshmi Crackers',
        description:'Lakshmi Crackers offer a blend of tradition and excitement. Named after the goddess Lakshmi, these crackers are typically used during Diwali celebrations. They produce loud bangs and are known for their bright, sparkling effects, adding a touch of tradition to any celebration',
        price:220,
    },
    {
        id:2,
        image: '/IMAGES/helicopter-img-3.jpg',
        title:'Helicopter Crackers',
        description:': Helicopter Crackers are a favorite among kids and adults alike. These crackers spin rapidly and lift off the ground, mimicking the flight of a helicopter. They produce a whistling sound and colorful sparks, creating an entertaining aerial display',
        price:320,
    },
    {
        id:3,
        image: '/IMAGES/Fancy-img-16.jpg',
        title:'Paper Crackers',
        description:'Paper Crackers are an eco-friendly option made primarily from paper materials. They produce a moderate noise level and bright, colorful sparks, making them suitable for all ages and ideal for quieter celebrations.',
        price:160,
    },
    {
        id:4,
        image: '/IMAGES/lakshmi-img-2.jpg',
        title:'15 Spot Crackers',
        description:' 15 Spot Crackers are designed to create multiple explosions in a single lighting. As the name suggests, these crackers burst into 15 small, bright spots, filling the sky with a stunning display of light and color. They are a must-have for any grand celebration.',
        price:300,
    },
    {
        id:5,
        image: '/IMAGES/ultra-pencil.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:6,
        image: '/IMAGES/Twinkling-Star.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:7,
        image: '/IMAGES/sivakasi-special-pencil.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:8,
        image: '/IMAGES/saram.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:9,
        image: '/IMAGES/Rocket-bomb.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:10,
        image: '/IMAGES/red-sparkers.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:11,
        image: '/IMAGES/red-bijilli.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:12,
        image: '/IMAGES/Power-bot.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:13,
        image: '/IMAGES/photo-flash.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:14,
        image: '/IMAGES/jolly-ranger.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:15,
        image: '/IMAGES/ground-chakkar.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:16,
        image: '/IMAGES/jolly-ranger.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:17,
        image: '/IMAGES/kurvi-img-1.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:18,
        image: '/IMAGES/red-sparkers.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:19,
        image: '/IMAGES/sivakasi-special-pencil.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:20,
        image: '/IMAGES/photo-flash.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:21,
        image: '/IMAGES/Power-bot.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:22,
        image: '/IMAGES/sivakasi-special-pencil.jpg',
        title:'Flower Bot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:400,
    },
    {
        id:23,
        image: '/IMAGES/Power-bot.jpg',
        title:'15 Spot Crackers',
        description:' Flower Bot Crackers are known for their beautiful floral patterns. When lit, they spin on the ground, releasing colorful sparks that resemble blooming flowers. These crackers are perfect for adding a touch of elegance to any festive event.',
        price:300,
    }


];